### ISSUE TITLE
AdGuard Home is offline or unreachable

### ISSUE THREAD

**Issue by protons3th** [davidmerrique/homebridge-adguardhome#30]
I have no issues accessing and using the same login for AdGuard Home on http://10.0.111.100/

No matter what I try, I can't get HomeBridge to connect to my AdGuard.

Runnine the following setup:
homebridge-adguardhome v1.7.2
Running a Portainer width HomeGuard Home Version: v0.107.36 

Here are my to settings: 

HomeBridge Conf:

    "accessories": [
        {
            "host": "10.0.111.100",
            "https": false,
            "port": 80,
            "username": "MyUserRemoved",
            "password": "MyPWRemoved",
            "name": "AdGuard",
            "type": "LOCK",
            "autoOnTimer": [
                0
            ],
            "hideNonTimer": false,
            "stateLogging": false,
            "_bridge": {
                "username": "0E:AB:3D:2D:4B:88",
                "port": 33735
            },
            "accessory": "AdGuardHome"
        }
    ]

Portainer Stacks:

version: "2.1"

services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    ports:
      - 53/tcp
      - 53/udp
      - 80/tcp
      - 3000/tcp
      - 67/udp
      - 68/tcp
      - 68/udp
      - 443/tcp
      - 853/tcp
    volumes:
      - /srv/adguard/adguard_work:/opt/adguardhome/work
      - /srv/adguard/adguard_conf:/opt/adguardhome/conf
    networks:
      macvlan:
        ipv4_address: 10.0.111.100 # this IP will show as a device on your router
      vlan_bridge:
        ipv4_address: 10.0.222.100 # Pick same last numbers as macvlan and use "vlan bridge subnet" (10)
    restart: unless-stopped

networks:
  macvlan:
    name: docker_macvlan
    driver: macvlan
    enable_ipv6: false
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 10.0.111.0/24 # Set to same subnet as your router and other devices
          ip_range: 10.0.111.100/27 # Available range from 192 to 224.
          gateway: 10.0.111.1 # This is your router IP

  vlan_bridge:
    name: docker_vlan_bridge
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.0.222.0/24 # subnet for all containers 
          ip_range: 10.0.222.100/27 # for easier use, set to same range as under macvlan (192 to 224 here)
          gateway: 10.0.222.1 # for easier use, set to same last number as your router

volumes:
  adguard_work:
    name: adguard_work
  adguard_conf:
    name: adguard_conf

**Comment by dwaan** [comment]
I see you’re using macvlan in your docker instance. Does your homebridge installed in the host server or in another docker instance inside the same server? 

From my experience using macvlan, even though you can access the ip from different computer in the same network, it’s unreachable inside the same server. So your problem might be the homebridge server can’t reach that ip. 

How ever, if it’s in different server, can you make sure you can the homebridge server can reach it using perhaps curl?

**Comment by protons3th** [comment]
Maybe I need to solve it by ot using macvlan, this is my HomeBridge compose:
``
version: '2'
services:

  homebridge:
    image: oznu/homebridge
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    ports:
      - 8581:8080
    volumes:
      - /srv/HomeBridge:/homebridge
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581

**Comment by dwaan** [comment]
You can try to replace the macvlan with host. I have similar setup like yours. Here’s my adguardhome docker compose:
```
version: '3.3'
services:
    run:
        container_name: adguardhome
        network_mode: host
        restart: unless-stopped
        volumes:
            - '/storage/adguardhome:/opt/adguardhome/work'
            - '/storage/adguardhome:/opt/adguardhome/conf'
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '67:67/udp'
            - '68:68/udp'
            - '80:80/tcp'
            - '443:443/tcp'
            - '443:443/udp'
            - '3000:3000/tcp'
            - '853:853/tcp'
            - '784:784/udp'
            - '853:853/udp'
            - '8853:8853/udp'
            - '5443:5443/tcp'
            - '5443:5443/udp'
        image: adguard/adguardhome
```
